# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    - name: package installation
      working-directory: ./labscript
      run: yarn
    - name: execute package
      run: chmod +x ./labscript/run && ./labscript/run
    - name: watch recusively current root directory
      run: ls -R .
    - name: push
      working-directory: ./labscript
      run: echo -e "maissacrement\n$PASS_GIT" | npm login --registry=https://npm.pkg.github.com
    - name: FREEZE installation
      working-directory: ./labscript
      run: rm -fr node_modules && yarn install --frozen
    - name: PUBLISH
      working-directory: ./labscript
      run: yarn publish
